stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy

build:
  stage: build
  image: openjdk:15
  script:
    - ./gradlew assemble
  artifacts:
    paths:
      - ./build/libs/usermanagmentaws.jar
test:
  stage: test
  image: openjdk:15
  script:
    - ./gradlew check --info

deploy:
  stage: desploy
  image: pulumi/pulumi-nodejs
  script:
    - cd deployment
    - export AWS_ACCESS_KEY_ID= "$AWS_ACCESS_KEY_ID"
    - export AWS_SECRET_ACCESS_KEY= "$AWS_SECRET_ACCESS_KEY"
    - pulumi up
